%***************************************************************************************
% ------------------------- Planetary stage No. 1 for a 5MW drivetrain -----------------
%
% Created by: Juan Gallego-Calderon, March 2014.
% Based on the data from the paper:
% Dabrowski, D., Natarajan, A.,"Assessment of Gearbox Operational Loads and
% Reliability under High Mean Wind Speeds"
%***************************************************************************************

%% Physical quantities
% gears
Zs          = 21;             % Number of teeth - sun
Zp          = 39;             % Number of teeth - planet
Zr          = 99;             % Number of teeth - ring
module      = 26.5;           % Normal module [mm]
alpha       = 20;             % Pressure angle [deg]
beta        = 15;             % Helix angle [deg]

rho         = 7850;           % material density [kg/m^3]
face_width  = 620e-3;         % Face width [mm]

rp_planet   = 1033.8/2*1e-3;    % pitch radius of the planet [m]
rp_sun      = 556.68/2*1e-3;    % pitch radius of the sun [m]
rp_ring     = 2624.3/2*1e-3;    % pitch radius of the ring [m] 

rb_planet   = rp_planet*cos(deg2rad(alpha));      % base radius of the planet [m]
rb_sun      = rp_sun*cos(deg2rad(alpha));         % base radius of the sun [m]
rb_ring     = (2*rp_planet+rb_sun)*cos(deg2rad(alpha));         % base radius of the sun [m]

m_planet    = 1616;             % mass of the planet [kg]
m_sun       = 1904;             % mass of the sun [kg]
m_ring      = 7330;             % mass of the ring [kg]
m_carrier   = 14315;            % mass of the carrier [kg]
I_planet    = 334.4;            % inertia of the planet [kg*m^2]
I_sun       = 64.9;             % inertia of the sun [kg*m^2]
I_ring      = 14685;            % inertia of the ring [kg*m^2]
I_carrier   = 7452;                  % inertia of the carrier [kg*m^2]

Ksp         = 2.15e+09;          % average sun-planet mesh stiffness [N/m]
Krp         = 3.09e9;            % average ring-planet mesh stiffness [N/m]

% bearings
kb_planet_xx   = 2*3e9;         % planet bearing stiffness [N/m]
kb_planet_xy   = 0;             % planet bearing stiffness [N/m]
kb_planet_yy   = 0;
kb_planet_zz   = 0;
kb_planet_wxwx = 0;
kb_planet_wywy = 0;
kb_sun          = 3.53e10;          % sun bearing stiffness [N/m]
kb_carrier_x    = 2*1.1e9; 
kb_carrier_y    = 2*1.1e9; 
kb_carrier_z    = 0; 
kb_carrier_thetax   = 0; 
kb_carrier_thetay   = 0; 
kb_ring     = 1e8;              % ring bearing stiffness [N/m]
ComplexityFlag = 2;             % regarding the conmplexity of the model:
            % 1 - 1D Torsional
            % 2 - 2D Translational/rotational
    

%% Create geometrical parameters vector to be used as an input to the model            
geoParameters_Planetary_No1 = [rb_planet,...
                               rb_sun,...
                               rb_ring,...
                               rp_planet,...
                               rp_sun,...
                               m_planet,...
                               m_sun,...
                               m_ring,...
                               m_carrier,...
                               I_planet,...
                               I_sun,...
                               I_ring,...
                               I_carrier,...
                               Ksp,...
                               Krp,...
                               kb_planet_xx,...
                               kb_planet_xy,...
                               kb_planet_yy,...
                               kb_planet_zz,...
                               kb_planet_wxwx,...
                               kb_planet_wywy,...
                               kb_sun,...
                               kb_carrier_x,... 
                               kb_carrier_y,... 
                               kb_carrier_z,... 
                               kb_carrier_thetax,... 
                               kb_carrier_thetay,... 
                               kb_ring,...
                               alpha,...
                               beta,...
                               Zs,...
                               Zp,...
                               Zr,...
                               ComplexityFlag];            

%% Dynamic simulation parameters
if ComplexityFlag == 1
    q0Planetary_01   = [0,0,0,0,0,0,0,0,0,0];         % initial condition vector for state-space model
elseif ComplexityFlag == 2;
    q0Planetary_01   = [0,...
                     rp_planet+rp_sun,0,0,...
                     -(rp_planet+rp_sun)*cos(pi-2*pi/3),(rp_planet+rp_sun)*sin(pi-2*pi/3),0,...
                     -(rp_planet+rp_sun)*cos(4*pi/3-pi),-(rp_planet+rp_sun)*sin(4*pi/3-pi),0,...
                     zeros(1,3)];
end

zetaPlanetary_01 = [0,0];                         % vector that contains alpha and beta parameters to defin Raleygh damping                        

clear rb_planet rb_sun rb_ring rp_planet rp_sun m_planet m_sun m_ring m_carrier ...
      I_planet I_sun I_ring I_carrier Ksp Krp kb_planet kb_sun kb_carrier kb_ring ...
      alpha beta Zs Zp Zr ComplexityFlag            
